# Generated by Django 5.0 on 2023-12-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='motocierras',
            fields=[
                ('id_motocierra', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('Fecha_ingreso', models.DateField()),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'motocierras',
            },
        ),
    ]
