# Generated by Django 5.0 on 2023-12-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsumicenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motocierras',
            name='precio',
            field=models.CharField(max_length=200),
        ),
    ]
