# Generated by Django 5.0 on 2023-12-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsumicenter', '0004_fumigadoras'),
    ]

    operations = [
        migrations.CreateModel(
            name='cortasetos',
            fields=[
                ('id_cortasetos', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('Fecha_ingreso', models.DateField()),
                ('precio', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'cortasetos',
            },
        ),
    ]
