# Generated by Django 5.0 on 2023-12-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsumicenter', '0007_sopladoras'),
    ]

    operations = [
        migrations.CreateModel(
            name='lubricantes',
            fields=[
                ('id_lubricante', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('precio', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'lubricantes',
            },
        ),
    ]
