# Generated by Django 5.0 on 2023-12-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsumicenter', '0008_lubricantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='accesorios',
            fields=[
                ('id_accesorios', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('EAN', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'accesorios',
            },
        ),
        migrations.CreateModel(
            name='accesorios_maquinas',
            fields=[
                ('id_maquinas', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('EAN', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'accesorios_maquinas',
            },
        ),
        migrations.CreateModel(
            name='EPP',
            fields=[
                ('id_EPP', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('EAN', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'EPP',
            },
        ),
        migrations.RenameField(
            model_name='ahoyadoras',
            old_name='precio',
            new_name='EAN',
        ),
        migrations.RenameField(
            model_name='cortasetos',
            old_name='precio',
            new_name='EAN',
        ),
        migrations.RenameField(
            model_name='fumigadoras',
            old_name='precio',
            new_name='EAN',
        ),
        migrations.RenameField(
            model_name='guadañas',
            old_name='precio',
            new_name='EAN',
        ),
        migrations.RenameField(
            model_name='lubricantes',
            old_name='precio',
            new_name='EAN',
        ),
        migrations.RenameField(
            model_name='motocierras',
            old_name='precio',
            new_name='EAN',
        ),
        migrations.RenameField(
            model_name='sopladoras',
            old_name='precio',
            new_name='EAN',
        ),
    ]
