# Generated by Django 5.0 on 2024-01-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsumicenter', '0009_accesorios_accesorios_maquinas_epp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accesorios',
        ),
        migrations.DeleteModel(
            name='accesorios_maquinas',
        ),
        migrations.DeleteModel(
            name='ahoyadoras',
        ),
        migrations.DeleteModel(
            name='cortasetos',
        ),
        migrations.DeleteModel(
            name='EPP',
        ),
        migrations.DeleteModel(
            name='fumigadoras',
        ),
        migrations.DeleteModel(
            name='guadañas',
        ),
        migrations.DeleteModel(
            name='lubricantes',
        ),
        migrations.DeleteModel(
            name='motocierras',
        ),
        migrations.DeleteModel(
            name='sopladoras',
        ),
    ]
