# Generated by Django 5.0 on 2024-01-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appsumicenter', '0012_delete_accesorios_delete_accesorios_maquinas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='accesorios',
            fields=[
                ('id_accesorios', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('EAN', models.CharField(max_length=100)),
                ('orden', models.CharField(max_length=100)),
                ('factura', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'accesorios',
            },
        ),
        migrations.CreateModel(
            name='accesorios_maquinas',
            fields=[
                ('id_maquinas', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('EAN', models.CharField(max_length=100)),
                ('orden', models.CharField(max_length=100)),
                ('factura', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'accesorios_maquinas',
            },
        ),
        migrations.CreateModel(
            name='ahoyadoras',
            fields=[
                ('id_ahoyadora', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('Fecha_ingreso', models.DateField()),
                ('EAN', models.CharField(max_length=200)),
                ('orden', models.CharField(max_length=100)),
                ('factura', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'ahoyadoras',
            },
        ),
        migrations.CreateModel(
            name='cortasetos',
            fields=[
                ('id_cortasetos', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('Fecha_ingreso', models.DateField()),
                ('EAN', models.CharField(max_length=200)),
                ('orden', models.CharField(max_length=100)),
                ('factura', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'cortasetos',
            },
        ),
        migrations.CreateModel(
            name='EPP',
            fields=[
                ('id_EPP', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('EAN', models.CharField(max_length=100)),
                ('orden', models.CharField(max_length=100)),
                ('factura', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'EPP',
            },
        ),
        migrations.CreateModel(
            name='fumigadoras',
            fields=[
                ('id_fumigadora', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('Fecha_ingreso', models.DateField()),
                ('EAN', models.CharField(max_length=200)),
                ('orden', models.CharField(max_length=100)),
                ('factura', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'fumigadoras',
            },
        ),
        migrations.CreateModel(
            name='guadañas',
            fields=[
                ('id_guadaña', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('Fecha_ingreso', models.DateField()),
                ('EAN', models.CharField(max_length=200)),
                ('orden', models.CharField(max_length=100)),
                ('factura', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'guadañas',
            },
        ),
        migrations.CreateModel(
            name='lubricantes',
            fields=[
                ('id_lubricante', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('EAN', models.CharField(max_length=100)),
                ('orden', models.CharField(max_length=100)),
                ('factura', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'lubricantes',
            },
        ),
        migrations.CreateModel(
            name='motocierras',
            fields=[
                ('id_motocierra', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('Fecha_ingreso', models.DateField()),
                ('EAN', models.CharField(max_length=200)),
                ('orden', models.CharField(max_length=100)),
                ('factura', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'motocierras',
            },
        ),
        migrations.CreateModel(
            name='sopladoras',
            fields=[
                ('id_sopladora', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('Fecha_ingreso', models.DateField()),
                ('EAN', models.CharField(max_length=200)),
                ('orden', models.CharField(max_length=100)),
                ('factura', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'sopladoras',
            },
        ),
    ]
