# Generated by Django 5.0 on 2024-01-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsumicenter', '0013_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorios_maquinas',
            name='EAN',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='accesorios_maquinas',
            name='codigo',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='accesorios_maquinas',
            name='factura',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='accesorios_maquinas',
            name='orden',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='accesorios_maquinas',
            name='serial',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
