# Generated by Django 5.0 on 2024-01-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsumicenter', '0014_alter_accesorios_maquinas_ean_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('EAN', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('orden', models.CharField(max_length=100)),
                ('factura', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
