# Generated by Django 5.0 on 2024-01-03 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsumicenter', '0015_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='fecha_ingreso',
            new_name='fecha',
        ),
    ]
