# Generated by Django 5.0 on 2024-01-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsumicenter', '0016_rename_fecha_ingreso_productos_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='truper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('EAN', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('orden', models.CharField(max_length=100)),
                ('factura', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'truper',
            },
        ),
    ]
