# Generated by Django 5.0.1 on 2024-01-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsumicenter', '0018_delete_accesorios_delete_accesorios_maquinas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='truper',
            name='cantidad',
            field=models.CharField(max_length=100),
        ),
    ]
